### ISSUE TITLE
BoundaryPointer类的bidirectional模式疑问

### ISSUE THREAD

**Issue by huhk-sysu** [laddie132/MRC-PyTorch#5]
在下面这段代码里，为了用Pointer网络计算从右至左的开始和结束概率，直接把Hr输入到另一个`UniBoundaryPointer`，并把输出的“开始概率"和”结束概率“对调，这段我不太理解，能否解释一下？
https://github.com/laddie132/Match-LSTM/blob/793f0ecd1b1deb69a690602d505cdffe35696be6/models/layers.py#L583-L587
在我的理解里，584行的`Hr`似乎应该使用`masked_flip`翻转后再输入吧？

是不是应该效仿`MatchRNN`的处理方式，用`masked_flip`处理`Hr`后输入，得到`beta`后再用`masked_flip`翻回来？

**Comment by laddie132** [comment]
这里的双向指的是，先预测start，再预测end；或者先预测end，再预测start。
对Hr翻转没有什么意义吧，因为在这上面只是做了一个attention的操作，没有引入时序信息。建议看一下`UniBoundaryPointer`的实现。

**Comment by huhk-sysu** [comment]
> 这里的双向指的是，先预测start，再预测end；或者先预测end，再预测start。
> 对Hr翻转没有什么意义吧，因为在这上面只是做了一个attention的操作，没有引入时序信息。建议看一下`UniBoundaryPointer`的实现。

谢谢，是我理解错了双向的意思，现在明白了。
